CREATE TABLE [dbo].[Customers]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[CreateDate] DATETIMEOFFSET NOT NULL,
	[CreatedBy] INT NOT NULL,
	[FullName] NVARCHAR(50) NOT NULL,
	[PhoneNumber] NVARCHAR(20) NOT NULL,
	[Address] NVARCHAR(70) NOT NULL,
	[PostCode] NVARCHAR(30) NOT NULL,
	[City] NVARCHAR(50) NOT NULL,
	[Email] NVARCHAR(60) NOT NULL,
	[PayRate] FLOAT NOT NULL,
	[Balance] FLOAT NOT NULL,
	CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED ([Id] ASC)
)
